config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :pics
  root "pics#index"


end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pics
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
before_action :find_pic , only: [:show , :edit , :update , :destroy]


def index
	@pics=Pic.all.order("created_at DESC")
end

def new
	@pic=current_user.pics.build
end

def create
	@pic = current_user.pics.build(pics_params)

	 if @pic.save
	 	redirect_to @pic , notice: "Yesss,it was posted!"
	 else
	    render 'new'	
     end
end


def edit
end

def update
	if @pic.update(pics_params)
		redirect_to pic_path
	else
	 render 'edit'
	end 	
end

def destroy
	@pic.destroy
	redirect_to root_path
end

 private

  def pics_params
  	params.require(:pic).permit(:title , :description)
  end	

  def find_pic
    @pic = Pic.find(params[:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Instagram
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags
  =stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

%body
  
  =yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html:{multiparts: true} do |f|
  - if@pic.errors.any?
    #errors
      %h2
      =pluralize(@pic.errors.count,"error")
      prevented this pic from saving
      %ul 
        - @pic.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.input :title
  .form-group  
    = f.input :description
    
  = f.button :submit, class: "btn btn-info"  

app/views/pics/edit.html.haml
%h1 Fix Pic

= render 'form'

= link_to "Cancel",root_path

app/views/pics/index.html.haml
- @pics.each do |pic|
  %h2= link_to pic.title ,pic

= link_to "Gram It",new_pic_path	

app/views/pics/new.html.haml
%h1 Post Pic

= render 'form'

= link_to "Back",root_path

app/views/pics/show.html.haml
%h2= @pic.title
%p=  @pic.description
Pic by
=@pic.user.email
%br
%br
= link_to "Home" ,root_path
= link_to "Edit",edit_pic_path
= link_to "Delete",pic_path , method: :delete ,data: {confirm: "Are you sure!"}